version: "2.20.2"

services:
  db:
    image: postgres:15
#    volumes:
#      - /Users/krishnae/SNA_Webtronics/db_data:/var/lib/postgresql/data
    container_name: db_app
    command: -p 5433
    expose:
      - 5433
    env_file:
      - .env_docker

  fastapi_app:
    build:
      context: .
    env_file:
      - .env_docker
    container_name: fastapi_app
    command:
      sh -c "alembic upgrade head && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db