"""7

Revision ID: 5332a9795df3
Revises: 90644e4662b9
Create Date: 2023-07-09 17:17:43.702172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5332a9795df3'
down_revision = '90644e4662b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('reaction', sa.Integer(), nullable=False))
    op.add_column('likes', sa.Column('reactkey2', sa.String(), nullable=True))
    op.drop_constraint('likes_like_key', 'likes', type_='unique')
    op.create_unique_constraint(None, 'likes', ['reactkey2'])
    op.drop_constraint('likes_username_fkey', 'likes', type_='foreignkey')
    op.drop_constraint('likes_post_id_fkey', 'likes', type_='foreignkey')
    op.drop_column('likes', 'dislike')
    op.drop_column('likes', 'username')
    op.drop_column('likes', 'post_id')
    op.drop_column('likes', 'like')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('like', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('likes', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('likes', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('likes', sa.Column('dislike', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key('likes_post_id_fkey', 'likes', 'post', ['post_id'], ['id'])
    op.create_foreign_key('likes_username_fkey', 'likes', 'users', ['username'], ['username'])
    op.drop_constraint(None, 'likes', type_='unique')
    op.create_unique_constraint('likes_like_key', 'likes', ['like'])
    op.drop_column('likes', 'reactkey2')
    op.drop_column('likes', 'reaction')
    # ### end Alembic commands ###
