"""2

Revision ID: 6573aa7d94fc
Revises: a0fec4cce37c
Create Date: 2023-07-27 00:17:19.982975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6573aa7d94fc'
down_revision = 'a0fec4cce37c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('post_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'post_id')
    # ### end Alembic commands ###
