"""4

Revision ID: 7aa33040e939
Revises: dd05963cae13
Create Date: 2023-07-08 03:54:16.251937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7aa33040e939'
down_revision = 'dd05963cae13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('posted_at', sa.TIMESTAMP(), nullable=True))
    op.drop_constraint('post_posted_username_fkey', 'post', type_='foreignkey')
    op.drop_column('post', 'pasted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('pasted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key('post_posted_username_fkey', 'post', 'users', ['posted_username'], ['username'])
    op.drop_column('post', 'posted_at')
    # ### end Alembic commands ###
