"""6

Revision ID: 90644e4662b9
Revises: 5b1a02c58dfd
Create Date: 2023-07-09 01:51:26.566939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90644e4662b9'
down_revision = '5b1a02c58dfd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'likes', ['like'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='unique')
    # ### end Alembic commands ###
