"""3

Revision ID: dd05963cae13
Revises: 8f16569c8da2
Create Date: 2023-07-08 02:49:20.346921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd05963cae13'
down_revision = '8f16569c8da2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('posted_username', sa.String(), nullable=True))
    op.add_column('post', sa.Column('title', sa.String(), nullable=True))
    op.add_column('post', sa.Column('body', sa.String(), nullable=True))
    op.drop_constraint('post_posted_user_id_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'users', ['posted_username'], ['username'])
    op.drop_column('post', 'posted_user_id')
    op.drop_column('post', 'text')
    op.alter_column('users', 'registered',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'registered',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('post', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('posted_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_posted_user_id_fkey', 'post', 'users', ['posted_user_id'], ['id'])
    op.drop_column('post', 'body')
    op.drop_column('post', 'title')
    op.drop_column('post', 'posted_username')
    # ### end Alembic commands ###
